(startLine=618 endLine=636 srcPath=/home/sonia/NewExperiment/guavaFilter/00697/guava-tests/test/com/google/common/util/concurrent/FuturesTest.java)
  public void testTransformAsync_getThrowsError() throws Exception {
    // This is an evil way to accomplish this, but it works currently.
    AbstractFuture<Object> input =
        new AbstractFuture<Object>() {
          @Override
          public Object get() {
            throw new MyError();
          }
        };

    ListenableFuture<Object> output = Futures.transformAsync(input, asyncIdentity());
    input.set("foo");
    try {
      output.get();
      fail();
    } catch (ExecutionException expected) {
      assertThat(expected.getCause()).isInstanceOf(MyError.class);
    }
  }

